# AK Dental - Basit Docker Compose Konfigürasyonu
# Geliştirme ve test için optimize edilmiş

version: '3.8'

services:
  # Ana web uygulaması - Python HTTP Server
  ak-dental-web:
    image: python:3.9-alpine
    container_name: ak-dental-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "-m", "http.server", "8000"]
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ak-dental-network

  # Nginx reverse proxy (opsiyonel)
  nginx:
    image: nginx:alpine
    container_name: ak-dental-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/usr/share/nginx/html:ro
    depends_on:
      - ak-dental-web
    restart: unless-stopped
    networks:
      - ak-dental-network

  # Mail test server (opsiyonel)
  mailhog:
    image: mailhog/mailhog
    container_name: ak-dental-mail
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    restart: unless-stopped
    networks:
      - ak-dental-network

networks:
  ak-dental-network:
    driver: bridge

# Kullanım:
# docker-compose -f docker-compose.simple.yml up -d
# docker-compose -f docker-compose.simple.yml down 